wandb_version: 1

exp_name:
  desc: null
  value: ppo
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.0025
seed:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 25000
torch_deterministic:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: CleanRL
wandb_entity:
  desc: null
  value: j
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709993915.0
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.13
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
